jobs:
  build:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - run: "tox -e py${{ matrix.pyver }}"
    strategy:
      matrix:
        pyver:
          - "36"
          - "38"
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2.1.0"
name: Greeting
on:
  pull_request: {}
  push: {}
